# -*- coding: utf-8 -*-
"""2024hack

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eSS6ZmlHoSdHESdlAKEDxufyzad5POy4
"""

!pip install openai

from openai import OpenAI
my_api_key = 'sk-7k11uzyaH2tRK8DrySl7pdSmIb9IP_u960zmNwH9szT3BlbkFJ2K8sULiZnWRTsb-phLPhFn2c7fmarfhuzmBg3pEQYA'

client = OpenAI(api_key=my_api_key)

test1 ="在滿都海的輔佐下，巴圖蒙克逐漸成長為一位合格的大汗。蒙古各部落重新團結起來，共同抵禦外敵。滿都海還為巴圖蒙克生下了八個子女，進一步鞏固了黃金家族的統治地位"
test2 ="1455年，蒙古草原，風雲變幻。大汗滿都魯駕崩，留下了一個權力真空和一個美貌的寡婦——32歲的滿都海。權力如同草原上的烈火，迅速點燃了各部落的野心。"
url = "https://i1.kknews.cc/owZhpXptjgC8TN6nrMeDNuWiTTmfFFxiMg/0.jpg"

'''
completion = client.chat.completions.create(
  model="gpt-4o",
  messages=[
    {"role": "system", "content": "I will give you an image url and sentence, please only return related score with float from zero to one"},
    {"role": "user", "content": url },
    {"role": "user", "content": test1 }
  ]
)

print(completion.choices[0].message)
'''

url = "https://cdn2.ettoday.net/images/5240/d5240869.jpg"

paragraph = "當心情不好時，你會想吃什麼？（示意圖／CFP）"

completion = client.chat.completions.create(
  model="gpt-4o",
  messages=[
    {"role": "system", "content": "you are a deepfake news dectector, please help find the content that will" },
    {"role": "user", "content": "I will give you an image url and this images's CHINESE STATEMENT, please only return two things: 1.Do you think the image is high related to the statement or not?(answer only 是 or 否 IN CHINESE) 2.According to Question1, why you think so?"},
    {"role": "user", "content": "The response should be Chinese" },
    {"role": "user", "content": url },
    {"role": "user", "content": paragraph }
  ]
)

print(completion.choices[0].message)

completion = client.chat.completions.create(
  model="gpt-4-turbo",
  messages=[
    {"role": "user", "content": "Descript the image"},
    {"role": "user", "content": "The response should be Chinese" },
    {"role": "user", "content": url }
  ]
)

print(completion.choices[0].message)

response = client.chat.completions.create(
  model="gpt-4-turbo",
  messages=[
    {"role": "system", "content": "you are a deepfake news dectector, please help find the content that will" },
    {
      "role": "user",
      "content": [
        {"type": "text",
         "text": "I will give you an image url and this images's CHINESE STATEMENT, please return two things: 1.a the image and the description CONFIDENCE SCORE(from 0 to 100) to show their relation 2. Why you give this score?"},
        {"type": "image_url",
         "image_url": {"url": url,},
        },
        {"type": "text",
         "text": paragraph},
        {"type": "text",
         "text": "Output format:<confidence score>\n<reason>"},
      ],
    }
  ],
  max_tokens=300,
)

print(response.choices[0].message.content)