name: aiguard_env
channels:
  - defaults
dependencies:
  - python==3.10
  - pip==24.2
  - pip:
    - pydantic==2.9.2
    - requests==2.31.0
    - connexion==3.0.0
    - connexion[flask]
    - connexion[swagger-ui]
    - connexion[uvicorn]
    - a2wsgi==1.10.6
    - fastapi==0.111.0
    - pyjwt==2.8.0
