name: aiguard_env
channels:
  - defaults
dependencies:
  - python==3.10
  - pip==24.2
  - pytorch==2.3.0
  - torchvision=0.18.1
  - pillow==10.4.0
  - tqdm=4.66.5
  - regex=2024.9.11
  - ftfy=5.8
  - pip:
    - pydantic==2.9.2
    - requests==2.31.0
    - connexion==3.0.0
    - connexion[flask]
    - connexion[swagger-ui]
    - connexion[uvicorn]
    - a2wsgi==1.10.6
    - fastapi==0.111.0
    - pyjwt==2.8.0
    - openai==1.52.0
